name: LaTeX Compile PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        example:
          - name: thmbox
            input-file: tests/thmbox/thmbox.tex
          - name: ams
            input-file: tests/ams/ams.tex
          - name: beamer
            input-file: tests/beamer/beamer.tex
    name: Build PDF - ${{ matrix.example.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup TeX Live
        uses: EasonSYC/latex-style-setup@main

      - name: Compile PDF - ${{ matrix.example.name }}
        uses: EasonSYC/latex-compile-pdf@main
        with:
          job-name: ${{ github.event.repository.name }}-${{ matrix.example.name }}
          input-file: ${{ matrix.example.input-file }}
          