name: LaTeX Compile PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDF

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup TeX Live
        uses: EasonSYC/latex-style-setup@main
      
      - name: Compile PDF
        uses: EasonSYC/latex-compile-pdf@main
        with:
          job-name: ${{ github.event.repository.name }}